### ISSUE TITLE
Saving configuration on 3.1 => 500 error

### ISSUE THREAD

**Issue by mkoistinen** [aldryn/aldryn-apphooks-config#28] opened 2015-04-22 14:47 UTC
The configuration gets saved, but there seems to be an internal redirect to an incorrect URL, that 500s. This leaves the front-end JS waiting forever.

````
[22/Apr/2015 09:41:54] "GET /en/admin/aldryn_faq/faqconfig/ HTTP/1.1" 200 4717
[22/Apr/2015 09:41:54] "GET /en/admin/jsi18n/ HTTP/1.1" 200 2372
[22/Apr/2015 09:41:54] "GET /en/admin/cms/page/resolve/?model=&pk= HTTP/1.1" 500 13440
````

I've tried multiple apphooks config'ed apps, and the results are the same in each.

**Comment by yakky** [comment] 2015-10-18 08:01
@mkoistinen can't reproduce this. Do you?

**Comment by yakky** [comment] 2015-12-20 22:40
@mkoistinen could you still reproduce this?

**Comment by yakky** [comment] 2016-02-08 20:04
@mkoistinen closing this, feel free to reopen if you can reproduce it

**Closed by yakky** 2016-02-08 20:04 UTC
